version: "3.9"

services:

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    ports:
      - "80:80"     # HTTP required for HTTP-01 challenge
      - "443:443"   # HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-acme:/letsencrypt
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=false"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=tu-email@ejemplo.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

#  nginx:
#    image: nginx:stable
#    container_name: nginx
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx/mime.types:/etc/nginx/mime.types:ro
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.nginx.rule=Host(`dentify-microservices.canadacentral.cloudapp.azure.com`)"
#      - "traefik.http.services.nginx.loadbalancer.server.port=80"
#    depends_on:
#      - service-discovery
#
#  nginx-updater:
#    build:
#      context: ./updater
#      dockerfile: Dockerfile
#    container_name: nginx-updater
#    environment:
#      - EUREKA_URL=http://eureka:8761/eureka/apps
#      - TEMPLATE_PATH=/etc/nginx-template/nginx.template
#      - OUTPUT_PATH=/etc/nginx/nginx.conf
#      - POLL_INTERVAL=15
#    volumes:
#      - ./nginx:/etc/nginx                    # comparte el mismo volumen con nginx
#      - ./nginx-template:/etc/nginx-template  # plantilla de entrada
#      - /var/run/docker.sock:/var/run/docker.sock
#    depends_on:
#      - service-discovery

  # Service discovery (Eureka)
  service-discovery:
    build: ./service-discovery
    container_name: service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MANAGEMENT_PORT=8079
      - MANAGEMENT_SERVER_PORT=8079
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics,drain
    restart: unless-stopped

  # API Gateway
  api-gateway:
    build: ./api-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`dentify-microservices.canadacentral.cloudapp.azure.com`)"
      - "traefik.http.routers.gateway.entrypoints=websecure"
      - "traefik.http.routers.gateway.tls=true"
      - "traefik.http.routers.gateway.tls.certresolver=le"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URL=http://service-discovery:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=api-gateway
      - MANAGEMENT_PORT=8079
      - MANAGEMENT_SERVER_PORT=8079
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics,drain
    depends_on:
      - service-discovery
    restart: unless-stopped
    deploy:
      replicas: 2

  # IAM service
  iam-service:
    build: ./iam-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://dentifydbserver.mysql.database.azure.com:3306/iam_db?sslMode=REQUIRED&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=dentify
      - SPRING_DATASOURCE_PASSWORD=Clinic123
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - EUREKA_URL=http://service-discovery:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=iam-service
      - MANAGEMENT_PORT=8079
      - MANAGEMENT_SERVER_PORT=8079
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics,drain
    depends_on:
      - rabbitmq
      - service-discovery
    restart: unless-stopped
    deploy:
      replicas: 2

  # Patient attention
  patient-attention-service:
    build: ./patient-attention-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://dentifydbserver.mysql.database.azure.com:3306/patient_attention_db?sslMode=REQUIRED&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=dentify
      - SPRING_DATASOURCE_PASSWORD=Clinic123
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - EUREKA_URL=http://service-discovery:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=patient-attention-service
      - MANAGEMENT_PORT=8079
      - MANAGEMENT_SERVER_PORT=8079
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics,drain
    depends_on:
      - rabbitmq
      - service-discovery
    restart: unless-stopped
    deploy:
      replicas: 2

  practice-management-service:
    build: ./practice-management-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://dentifydbserver.mysql.database.azure.com:3306/practice_management_db?sslMode=REQUIRED&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=dentify
      - SPRING_DATASOURCE_PASSWORD=Clinic123
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - EUREKA_URL=http://service-discovery:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=practice-management-service
      - MANAGEMENT_PORT=8079
      - MANAGEMENT_SERVER_PORT=8079
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics,drain
    depends_on:
      - rabbitmq
      - service-discovery
    restart: unless-stopped
    deploy:
      replicas: 2

  service-catalog-service:
    build: ./service-catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://dentifydbserver.mysql.database.azure.com:3306/service_catalog_db?sslMode=REQUIRED&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=dentify
      - SPRING_DATASOURCE_PASSWORD=Clinic123
      - EUREKA_URL=http://service-discovery:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=service-catalog-service
      - MANAGEMENT_PORT=8079
      - MANAGEMENT_SERVER_PORT=8079
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics,drain
    depends_on:
      - service-discovery
    restart: unless-stopped
    deploy:
      replicas: 2

  clinic-management-service:
    build: ./clinic-management-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://dentifydbserver.mysql.database.azure.com:3306/clinic_management_db?sslMode=REQUIRED&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=dentify
      - SPRING_DATASOURCE_PASSWORD=Clinic123
      - EUREKA_URL=http://service-discovery:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=clinic-management-service
      - MANAGEMENT_PORT=8079
      - MANAGEMENT_SERVER_PORT=8079
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics,drain
    depends_on:
      - service-discovery
    restart: unless-stopped
    deploy:
      replicas: 2

  appointment-service:
    build: ./appointment-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://dentifydbserver.mysql.database.azure.com:3306/appointment_db?sslMode=REQUIRED&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=dentify
      - SPRING_DATASOURCE_PASSWORD=Clinic123
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - EUREKA_URL=http://service-discovery:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=appointment-service
      - MANAGEMENT_PORT=8079
      - MANAGEMENT_SERVER_PORT=8079
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics,drain
    depends_on:
      - rabbitmq
      - service-discovery
    restart: unless-stopped
    deploy:
      replicas: 2

  autoscaler-gateway:
    build: ./updater
    environment:
      - SERVICE=api-gateway
      - MIN_REPLICAS=1
      - MAX_REPLICAS=4
      - MANAGEMENT_PORT=8079
      - CPU_UP_THRESHOLD=70
      - CPU_DOWN_THRESHOLD=30
      - COOLDOWN=120
      - DRAIN_TIMEOUT=40
      - CHECK_INTERVAL=15
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - api-gateway

  autoscaler-iam:
    build: ./updater
    environment:
      - SERVICE=iam-service
      - MIN_REPLICAS=1
      - MAX_REPLICAS=4
      - MANAGEMENT_PORT=8079
      - CPU_UP_THRESHOLD=70
      - CPU_DOWN_THRESHOLD=30
      - COOLDOWN=120
      - DRAIN_TIMEOUT=40
      - CHECK_INTERVAL=15
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - iam-service

  autoscaler-patient:
    build: ./updater
    environment:
      - SERVICE=patient-attention-service
      - MIN_REPLICAS=1
      - MAX_REPLICAS=4
      - MANAGEMENT_PORT=8079
      - CPU_UP_THRESHOLD=70
      - CPU_DOWN_THRESHOLD=30
      - COOLDOWN=120
      - DRAIN_TIMEOUT=40
      - CHECK_INTERVAL=15
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - patient-attention-service

  autoscaler-practice:
    build: ./updater
    environment:
      - SERVICE=practice-management-service
      - MIN_REPLICAS=1
      - MAX_REPLICAS=4
      - MANAGEMENT_PORT=8079
      - CPU_UP_THRESHOLD=70
      - CPU_DOWN_THRESHOLD=30
      - COOLDOWN=120
      - DRAIN_TIMEOUT=40
      - CHECK_INTERVAL=15
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - practice-management-service

  autoscaler-service:
    build: ./updater
    environment:
      - SERVICE=service-catalog-service
      - MIN_REPLICAS=1
      - MAX_REPLICAS=4
      - MANAGEMENT_PORT=8079
      - CPU_UP_THRESHOLD=70
      - CPU_DOWN_THRESHOLD=30
      - COOLDOWN=120
      - DRAIN_TIMEOUT=40
      - CHECK_INTERVAL=15
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - service-catalog-service

  autoscaler-clinic:
    build: ./updater
    environment:
      - SERVICE=clinic-management-service
      - MIN_REPLICAS=1
      - MAX_REPLICAS=4
      - MANAGEMENT_PORT=8079
      - CPU_UP_THRESHOLD=70
      - CPU_DOWN_THRESHOLD=30
      - COOLDOWN=120
      - DRAIN_TIMEOUT=40
      - CHECK_INTERVAL=15
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - clinic-management-service

  autoscaler-appointment:
    build: ./updater
    environment:
      - SERVICE=appointment-service
      - MIN_REPLICAS=1
      - MAX_REPLICAS=4
      - MANAGEMENT_PORT=8079
      - CPU_UP_THRESHOLD=70
      - CPU_DOWN_THRESHOLD=30
      - COOLDOWN=120
      - DRAIN_TIMEOUT=40
      - CHECK_INTERVAL=15
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - appointment-service

volumes:
  rabbitmq_data:
  traefik-acme: